### ISSUE TITLE
MacOS builds disabled?

### ISSUE THREAD

**Issue by stevengj** [conda-forge/pymeep-feedstock#38]
We used to have MacOS builds, I thought, but they seem to be disabled for recent releases.  @oskooi, @ChristopherHogan?

**Comment by oskooi** [comment]
According to @ChristopherHogan, restoring the macOS build will require several days of work unfortunately which we haven't gotten around to yet.

**Comment by stevengj** [comment]
What changed to break this?

**Comment by oskooi** [comment]
I think the issue is related to package conflicts involving the `libblas` and `libcblas` dependencies and `numpy` which are tricky to resolve.

**Comment by stevengj** [comment]
You need to make sure everything is built with the same BLAS — Anaconda numpy uses MKL by default, I think, so Harminv and MPB need to be built against this as well, but this should be straightforward (adding the dependency to the package, and passing the appropriate `configure` args).

**Comment by oskooi** [comment]
Yes, there seems to be an inconsistency with the BLAS library that is used to compile the Conda package for Harminv  and MPB:

https://github.com/conda-forge/harminv-feedstock/blob/f34d05bbcdd5be76989b880ef7b7d992a16d52c1/recipe/build.sh#L3

https://github.com/conda-forge/mpb-feedstock/blob/c93f4331016aedb411bdd03709f74c3c97a75a9f/recipe/build.sh#L13

Harminv is compiled with OpenBLAS but MPB is not.

**Comment by oskooi** [comment]
Without any changes to the feedstock, the macOS Conda package automatically updated to `v1.15.0` yesterday: https://anaconda.org/conda-forge/pymeep. Not sure how/why this happened but it would be good to verify that the macOS Conda package is indeed `1.15` (rather than a mislabeled badge) by inspecting the version number of the module:
```py
import meep as mp
print(mp.__version__)
```

**Comment by stevengj** [comment]
I checked the tarball and verified that it is really 1.15, so it seems this is fixed.
